### Get all rules
GET http://localhost:8000/api/v1/rules HTTP/1.1
Content-Type: application/json

### Get specific rule
GET http://localhost:8000/api/v1/rules/rule3 HTTP/1.1
Content-Type: application/json

### run a rule
POST http://localhost:8000/api/v1/rules/rule2
Content-Type: application/json
